export enum Ordering{
  "FIDE_RATING" = "FIDE_RATING",
  "NATIONAL_RATING" = "NATIONAL_RATING",
  "XADREZSUICO_RATING" = "XADREZSUICO_RATING",
  "INTERNAL_RATING" = "INTERNAL_RATING",
  "BORNDATE" = "BORNDATE",
  "ALPHABETICAL" = "ALPHABETICAL",



  "START_NUMBER" = "START_NUMBER"
}
